### ISSUE TITLE
Contribution guidelines?

### ISSUE THREAD

**Issue by omgitsraven** [naelstrof/KoboldKare#100]
I know the readme already has this as a todo, but I thought I'd at least ask for the short version -- are there any particular guidelines for what changes are/aren't likely to be accepted, or maybe more importantly, what other people might already be working on?  There's a few things I'm tempted to try, but I'm not sure if I should check somewhere before I bother....

Just as examples, I'm thinking like:
- Fluid decal maps stored as 2D SDFs (for smoother edges without using any more memory, and should be only slightly slower drawing); easy in theory but would mean going around making changes to every shader that can draw fluid decals, which feels like the kind of thing that would accidentally clobber someone else's work
- Some sort of item that would let you view another kobold's meters without having to bodyswap just to see them; at a glance the _functionality_ looks like it should be easy to implement, but I wouldn't know where to start in terms of deciding what the item should look like, what it should cost, etc; is there concern about figuring that out 'properly', or can a contributor just kind of do whatever?

**Comment by naelstrof** [comment]
Yeah I'd love some advice on how to even create contribution guidelines, currently I'm just allowing people to contact me and I'm letting people know what I'm willing to accept 😅 
I wouldn't know how to even automate or standardize this process, I don't have much experience managing contributions.

Using 2D SDFs would be an incredibly intelligent solution to dilate and smooth decals. It's already set up to take an arbitrary shader for dilation purposes-- If you want to work on that, KoboldKare currently uses my addon package here for decals: https://github.com/naelstrof/SkinnedMeshDecals
It'd make sense to just run an [eikonal equation shader](https://www.shadertoy.com/view/MtK3zD) a dozen times on a decal right when it's changed-- If you're familiar with command buffers this would actually be pretty easy. If you can get it working in the example project for SkinnedMeshDecals-- KoboldKare already just downloads it as a package. 

As for scanning meters/genetics, it'd be perfectly acceptable to me to have alternative scanners. There's a scanner in the game already, just color it another color and have it display different stats on scan. 

Both your ideas are wonderful and have a really high chance of being accepted, as long as I can follow along what you've done.

**Comment by omgitsraven** [comment]
Oh that eikonal shader looks good, but you don't even need it -- if you make the splats themselves into SDFs (like, at editor time), then you can just blit the new splats into the existing map with a Min blend mode and it'll come out accurate!  So the only extra work for the GPU is just the tiny step of rounding the alpha (or doing a really narrow smoothstep on it) when outputting the map in a fragment shader.

Honestly, I think this has done a pretty good job of establishing a useful contribution guideline: if you intend to add something, post a github issue describing your idea first, to get feedback on how to tackle it; I'm glad I didn't get work underway on changing the shaders before realising they come a separate package and I should be making the changes there!  (I think I would have gone "wait a minute I'm in the Packages folder" sooner or later, but, still...)   Also, I wouldn't have guessed that it'd be alright to just reuse the existing scanner asset, but that does make way more sense, at least to get the feature out the door (it would be fun to make a new asset for it too, but that can come later, no sense holding the feature back just for that...)

**Comment by naelstrof** [comment]
Oh awesome, you're right about the SDFs. I was thinking about how that would conveniently solve the UV-edge problem too:
![image](https://user-images.githubusercontent.com/1131571/210292721-4f3a0054-8e4a-43b6-8cf0-129956ed2290.png)
I ended up solving it by writing a pretty dumb 1.5 pixel dilation shader. Honestly it seems better to simply do both, have SDF rendered decals-- with the dilation shader on top to fix up the seams.

And I agree! I'll make some contribution lines in the readme in a bit, then I'll close this issue with the commit I make.

**Comment by omgitsraven** [comment]
Oh wow, I'm realising I'd actually totally misunderstood what the dilation was for -- I assumed that was to hide seams between *separate* maps, i.e. adjacent ground tiles; I hadn't thought about precision problems with drawing into UV space like that.    (Now I'm actually worried that SDFs would make these seams more prominent, but probably not enough so to be worth worrying about...)  But why is the dilation pass even necessary any more, now that Unity supports conservative rasterization?  Is there PC-level hardware that still can't do it?

**Comment by naelstrof** [comment]
Oh shoot my bad, we might want to continue this conversation in another issue anyway-- perhaps in the relevant repository as well haha.

Unity may support conservative rasterization, but it has problems dealing with both transparency and some hardware doesn't support it at all. The dilation pass is totally required to prevent the seams, you can experience it in-game by setting the decal quality below 50%-- seams should suddenly become very apparent as I disable the dilation pass at that point.
