### ISSUE TITLE
Pinned objects that are destroyed via explosion keep the pins there

### ISSUE THREAD

**Issue by crustationstation** [naelstrof/KoboldKare#103]
Pinning a dildo in place, then adding water and potassium to it to make it explode, destroys the dildo but not the pins, leaving the UI elements for unpinning.

**Comment by naelstrof** [comment]
Hahaha, when I went to replicate it, it's not that the pins got stuck, it's that the dildo got shrunk so small it was basically invisible. I've added a minimum scale so they don't shrink so small that you cannot see them.
