### ISSUE TITLE
Lack of customisation

### ISSUE THREAD

**Issue by Jaquinthe** [naelstrof/KoboldKare#113]
![image](https://user-images.githubusercontent.com/122505096/211969137-9c8a19c1-7c38-436d-88e8-3030369edb2c.png)
a discussion me and someone had in a discord regarding some changes we wished to see.
the screenshot has the important part of the discussion, but in case the image does not send through:
an improvement we would like to suggest is more variations in body shapes, vaginas, color patterning, and clothing choices. things to really customize our characters that we are playing with, and give a reason for people to really play the breeding mechanics for more than just hue adjustment.

**Comment by FelisMoon** [comment]
Made an Issue suggesting a possible system to overhaul customization in a way that only tags and new models have to be added :
https://github.com/naelstrof/KoboldKare/issues/115

**Comment by naelstrof** [comment]
While this would undoubtedly make the game better, it is too much work to implement. It would also make it harder for modders to create custom characters.
