### ISSUE TITLE
StreamingAssets folder content

### ISSUE THREAD

**Issue by gff1979** [naelstrof/KoboldKare#114]
This doesn't seem to be there when I build, though the game works, just without text from the localization and a few other things. Is that folder only included with the itch.io/Steam official build?

**Comment by naelstrof** [comment]
Just need to build addressables.

**Comment by naelstrof** [comment]
You can find instructions here: https://github.com/naelstrof/KoboldKare/blob/master/CONTRIBUTING.md

**Comment by gff1979** [comment]
Heh, duh-doi. Thanks for the help.
