### ISSUE TITLE
Overhaul: Split Kobold Model Variations and Equipment System

### ISSUE THREAD

**Issue by FelisMoon** [naelstrof/KoboldKare#115]
Idea is fully **conceptual.** If it does not fit the vision of the game, Ill be happy to close it.

I always thought that the variation in looks of the Kobolds themselves is lackluster. besides body morphing and Kobolds with Psuedo-Equipped Penis Items, You are always playing with the same looking models. So i came up with a bare bones idea for a system that allows further customization of both npc and player models.
This system would allow easy implementation of stuff like: Fully independent (No Vagina Inside) Penis skin variations that are not locked equipment,  Vagina Skin Variations,  Breast Skin Variations,  Head Shape variations,  Full Clothing Items that make use of Kobold stats, and I'm sure there is room to be creative and do more.

Anyway, _it consists of this:_

Separate the Kobold model by **Head/ UpperBody/ LowerBody/** (optionally **Hands/ Feet/** ?) with the intention of match and mixing variations. Tag Models by: _Male/ Female/_

Remove all Penis Equipment and tie them to Male/ **LowerBody/** model meshes.

Generated Kobolds will now choose a combination of **Head/ UpperBody/ LowerBody/** models based in **Genetics** and **Gender.**

 This system allows the creation of new, extra equipment-based models. (Lets call them **ModelOverrides** ? **Wearables** ? ) This would be equipment Items that override the default Nude kobold model of its dedicated part, while still being affected by the Kobold's body stats. Tag These models by: _MaleEquipment/ FemaleEquipment/_
 
 In order for this to work properly, Kobolds need a default model combo assigned by birth, (That cannot be changed without breeding) and active equipment slots for overriding that part of the model.
Also, It will require making into _incompatible_ regular equipment with certain **ModelOverride Wearables** depending on Clipping Issues. (I'd Suggest just hiding incompatible equipment, but let it be equipped anyway)

Please note that extra stuff like allowing certain Wearables to use or not use certain holes and genitals would be needed as well, But a Tag based system can also be used here,
 
 Here are some examples of how can this be used :
 - More genetic variations obtained by breeding, that offer different Head, Boob, Penis and Vagina shapes and types.
 - Clothes of any kind
 - SwimSuits or other Breast Holding clothes that change the shape of the Boobs, But use the _Size_ of the Kobold stats.
 - Clothes that hide genitals completely, like pants and shirts. (That create bulges on big sizes?)
 - Hides the Vagina inside Penis models by making them into their own models, Like breasts.

**Comment by naelstrof** [comment]
While this would undoubtedly make the game better, it's out of scope. I want to make it as easy as possible to add custom characters as well. I'd be willing to look at it again after modding is ready, but I have a feeling that modding alone would solve this issue.

**Comment by FelisMoon** [comment]
Man, That's a shame :T I get it tho, people are staring to have an idea of how modding works, and replacing with a system like this would limit them back to roots. Kobolds randomizing body parts would also mean custom races are harder to make since there are more Kobold models to replace. On the other hand, custom characters are able to be added trough the ModelOverride Items without altering Kobolds themselves... but thats off the point. :P 

Oh well, good luck getting mod compatibility ready! :D
