### ISSUE TITLE
Casino bgm stops while ragdolling

### ISSUE THREAD

**Issue by Detwand** [naelstrof/KoboldKare#137]
The bgm of the casino is muted, when in ragdoll mode and returns to the start, once player returns into a playable state (rigid).

Demonstration: 
https://user-images.githubusercontent.com/122717689/212763350-02b1cfa1-4e9a-42f2-b1e0-404d674a63e4.mp4

**Comment by FelisMoon** [comment]
Also worth noting that both ambience music and casino music can play at the same time by doing this.

**Comment by naelstrof** [comment]
Oh yeah this is due to my aggressive culling of audio sources. Definitely a bug.

**Comment by Detwand** [comment]
Issue has been spotted in the most recent patch 501_F1A2F670 again. Same details.
