### ISSUE TITLE
Suggestion: mushroom selling price adjustment

### ISSUE THREAD

**Issue by Detwand** [naelstrof/KoboldKare#138]
I just learned, that the player receives 40 dollars (about as much as an average kobold) just from selling a single mushroom, so I thought I may put this up here
Unlike kobolds, mushrooms can be sold in great amounts with ease just with a single well bred strong kobold (that has consumed multiple generations of meat).

You can make thousands of bucks with little to no effort after a little time investment.
I don't know how the economy is intended to work, but knowing this you can knockout any money shortage with ease, rendering breeding for money as redundant and the currency itself looses worth, if it is easily acquired with no sweat (basically inflation). 

That is why I think it would be apropriate to lower the selling price to less than ten dollars.

**Comment by naelstrof** [comment]
Oh yeah, whoops, mushroom juice used to be a 2nd tier reagent-- like growth serum. The price was left really high as an accident.

**Comment by Detwand** [comment]
It seems that the price for mushrooms is still 40 $ on the most recent patch.
