### ISSUE TITLE
Body swap mashine WASD input bug

### ISSUE THREAD

**Issue by Detwand** [naelstrof/KoboldKare#139]
Back again with a new bug. This time featuring the body swap mashine

1. Use the mashine
2. Hold any of the WASD keys (other inputs I have tried didn't yield any bug result) until the process is finished
3. The kobold you just swapped from starts moving infinitely according to the wasd key, that you pressed during the swapping process

The only way to resolve this issue is to swap again, but without wasd input in the process.

This is easily recreatable.
Here a demonstration using the S key as my chosen input for the bug and fixing it with another swap.

https://youtu.be/BSoCMb_BSus

**Comment by naelstrof** [comment]
Great report and investigation.

**Comment by Detwand** [comment]
I am reporting that the same issue has popped up again.
Exactly the same one. 
Nothing different from what is already mentioned above.

**Comment by Detwand** [comment]
It seems that the issue has returned in the same fashion. Same way of recreation.
I am plaiyng on version 501_F1A2F670, which should be the most recent version, if I a not wrong.

**Comment by naelstrof** [comment]
Oh that's not the most recent version. The public version of kk is behind. It'll update soon.
