### ISSUE TITLE
Massive FPS low, when pressing Mouse2 

### ISSUE THREAD

**Issue by Detwand** [naelstrof/KoboldKare#145]
I don't know what is causing this, but the game becomes incredibly laggy (-50 frames drop from 70 on max graphics), when I press Mouse2 button repeatedly, regardless of holding an item. 

I am only pressing M2 that's all.

Video demostrating the issue: 
https://youtu.be/k2YxX9d4Ep0

**Comment by naelstrof** [comment]
Do you mind sharing your Player.log? You can find it here:

`C:\Users\<username>\AppData\LocalLow\Naelstrof\KoboldKare\Player.log`

You can also type this into explorer:
`%UserProfile%\AppData\LocalLow\Naelstrof\KoboldKare\`

Chances are that there's an exception and its spamming the console, I need this to continue, as I do not get the lag spikes when I hit M2!

**Comment by Detwand** [comment]
[Player.log](https://github.com/naelstrof/KoboldKare/files/10457956/Player.log)

Here you go. Just tested it again and it is global across saves.

**Comment by GreenboxGames** [comment]
Does it also make the emptying of container projectiles eject at a steep angle instead of straight out? I ran into this problem too while trying to figure out that bug. It doesn't always happen but when it does, emptying things flings them way up not forward, and right clicking rapidly lags badly.
