### ISSUE TITLE
Cheat to give all store upgrades?

### ISSUE THREAD

**Issue by RWsYiffyMind** [naelstrof/KoboldKare#150]
Whenever I'm trying to test something involving farm hardware in the editor, I can unlock the necessary stars and money with cheats, but I still have to run all the way to town and back to actually purchase them....    Is there a reason there isn't a cheat for this, or would it be alright to add one?

**Comment by naelstrof** [comment]
Yeah there totally needs to be a cheat for it. It can probably just search the scene for all Contracts and just purchase them all. It can softlock the game, but using /skip people can un-softlock it. Which is fine.
