### ISSUE TITLE
Spamming right-click (to empty container) lags FPS

### ISSUE THREAD

**Issue by GreenboxGames** [naelstrof/KoboldKare#159]
Quickly pressing the right mouse button to tip or splash the container, even when empty, causes the FPS to drop dramatically causing severe lag.

**Comment by GreenboxGames** [comment]
Okay, I think my trouble with emptying accuracy is related to this. I'm not able to reproduce either this lag bug or the one where the content drops fly more upwards from containers when splashing, but if I had been paying attention last night I would have put the two together... I will try to reproduce in Current Steam Build, mod-branch, and master if I can, to see what might be going on.

**Comment by Detwand** [comment]
https://github.com/naelstrof/KoboldKare/issues/145#issue-1548099258
I think this might be the same issue as this one
