### ISSUE TITLE
Can't `/equip` any more?

### ISSUE THREAD

**Issue by RWsYiffyMind** [naelstrof/KoboldKare#165]
As of the latest commit (not sure when it changed), typing `/equip EquineDick` gives "Failed to find equipment with name EquineDick", even though `EquineDick` still appears when you type `/list`.  This seems to be the case for every equipment I've tried, like `Gloves`, etc.  Has the syntax changed or is this a bug?

**Comment by naelstrof** [comment]
Dicks are no longer equipment. Going to need a cheat that changes genetics. Haven't gotten around to it yet.
This was to simplify adding content to the game for modders.
