### ISSUE TITLE
Bug where Fatness resets to 0 on using energy when at negative values via Mushroom Juice

### ISSUE THREAD

**Issue by Raziel-Soulshadow** [naelstrof/KoboldKare#169]
Apparently fatness resets to zero due to clamping put into place during energy usage. Pretty sure it's an easy fix by going to the Kobold.cs script and changing

        if (diff < 0f && photonView.IsMine) {

on line 245 (I think, part of the SetEnergyRPC function) to say:

        if (diff < 0f && GetGenes().fatSize > 0 && photonView.IsMine) {

instead. Basically, it checks if fatness is zero or below and doesn't change it if that's the case... which it shouldn't since this code is specifically for fat loss only. Mind, I'm working off the code from a couple weeks ago, so it might have changed since then... but you probably get the idea.

**Comment by naelstrof** [comment]
Nice bug report and investigation, thank you!
