### ISSUE TITLE
Remove cap sensitivity when using commands.

### ISSUE THREAD

**Issue by NyekoNyekoNyeko** [naelstrof/KoboldKare#172]
When attempting to use commands such as /give or /equip, if the player uses the incorrect capitalization they will not be able to create the item they want. This is minor but a mildly annoying issue for players using mods, as attempting to spawn items in that can have any kind of capitalization strategy can leave them guessing names over and over again. ( This code base uses PascalCase but modders may not. )

There's only one way to fix as far as I can tell ( without major rewrites ), and it involves modifications in the following files.
"CommandGive.cs"
"ReagentDatabase.cs"
"EquipmentDatabase.cs"
"PlantDatabase.cs"

It simply adds "To.Lower()" to database searches and for loops to failed dictionary look-ups.
This shouldn't impact performance as the /give and /equip command is not run every frame, and even then the equipment/plant/reagent database ( along with the photon network prefab-pool-resource-cache ) shouldn't be big enough to cause frame drops if searched through every frame.

If there are any thoughts or objections to this fix, let me know. If not, I can submit a pull request by the end of the day.

*NOTE:
Technically this issue can be subverted by not relying on commands at all and instead using something similar to a "minecraft creative inventory", but that would require significantly more time to create. The idea should not be ignored though, as it would be a good for accessibility.*

**Comment by naelstrof** [comment]
The only reason it's case-sensitive is because photon expects exact matches. My fear with ToLower is that it is strictly a English thing, however I believe the invariant ToLower would work fine without causing something like the lower-case Cyrillic "C" being "r" or similar.

What would be nice is an auto-complete. Or a fuzzy suggestion engine. I fear making database matching being looser since that can cause issues in the future as more things get added to the game.

**Comment by NyekoNyekoNyeko** [comment]
That's completely reasonable. Then do you think something like a "Creative Mode" GUI listing all available equipment would be a better solution? An auto-complete would be interesting but it's implementation would be at the very least non-trivial, and a GUI would be much more appreciated by casual users, since most are scared off by command-lines.

**Comment by naelstrof** [comment]
I will revisit this after modding gets completed. I like the idea of a friendly GUI, but it takes a significant amount of work compared to a fuzzy suggestion engine. We already have a list of strings that it could match. Using something like [FuzzySharp](https://github.com/JakeBayer/FuzzySharp) to score and give suggestions would be pretty trivial.

It would help tremendously if "Egg" and "Ice" didn't match both reagents and existing networked prefabs. Maybe the /give command should be split up. I'd like to refactor many of the systems.

**Comment by NyekoNyekoNyeko** [comment]
That's fair, I'll close this issue and then create 2 new ones concerning the use of FuzzySharp and a Friendly Gui.
