### ISSUE TITLE
since 501: Picking up a player character with shift (physics grab) causes them to teleport to the last location in which they ragdolled

### ISSUE THREAD

**Issue by rahisauce** [naelstrof/KoboldKare#177]
When picking up a player character with shift-grab, when they enter ragdoll mode, their character is swiftly moved to (i suspect) the last place they ragdolled. This can be mitigated by the "victim" first pressing F to ragdoll, before being picked up. This only appeared since the optimisations to ragdolling made in Patch 501.

**Comment by naelstrof** [comment]
Good catch, yeah after I separated ragdolls into a single position and some 13 bit rotations-- I forgot to create dummy hip position packets when they weren't ragdolled. Should be fixed now!
