### ISSUE TITLE
Broken online save

### ISSUE THREAD

**Issue by AviYol** [naelstrof/KoboldKare#183]
So far as i am aware the issue is from a late progress save being used in a online session. Every time someone joins shortly after they immediately get disconnected. i havent been able to find any kind of source or cause but it does seem to be constant when i delete a older save to make a new one it is still there. 
[1677735988.txt](https://github.com/naelstrof/KoboldKare/files/10868208/1677735988.txt)
hopefully you can find the issue and it will be simple to fix.

**Comment by naelstrof** [comment]
Couldn't replicate the issue on [487e652](https://github.com/naelstrof/KoboldKare/commit/487e652b1c16e39f2e35f3234f7ce93b741b1499).
