### ISSUE TITLE
You can still purchase from the board after you have bought everything

### ISSUE THREAD

**Issue by Godeken** [naelstrof/KoboldKare#189]
![image](https://user-images.githubusercontent.com/121225143/222745917-bc42b1db-54e5-4717-a6d6-6a5cf2b88606.png)
Pressing E then minus 80 cash from you every time...

**Comment by naelstrof** [comment]
Can't replicate.
![image](https://user-images.githubusercontent.com/1131571/222848543-78dc9081-5c55-4123-9bd2-d5bc3cfecce0.png)
