### ISSUE TITLE
Genetics - Kids are bigger than parents

### ISSUE THREAD

**Issue by Godeken** [naelstrof/KoboldKare#192]
Not sure if its a feature or not - the kids "Assets" are bigger than the parents.
However, the amount they "expel" is the same as the parents, could this be a scaling issue on the parents or on the kids?
[Image](https://user-images.githubusercontent.com/121225143/222900790-858157e2-b0f1-456d-aaae-126312106f82.png)

**Comment by naelstrof** [comment]
Ohh, I found the "issue". I had buffed female kobold genetics, they have a hidden dick size and ball size stat which was much higher on average than male kobolds. This is a silly buff that nobody would be able to see without a genetics scanner though.
