### ISSUE TITLE
Forced to be one with Nature 

### ISSUE THREAD

**Issue by OfficialMonsterCrush** [naelstrof/KoboldKare#200]
In the beta upon equipping your Kobold or other Kobolds with wearable items then saving and leaving no matter the time frame in-between the save and the exit once loading back in the game erases all clothing that any Kobold was wearing at the time with the exception of a few, I've played around with this in multiple save files and the max amount of clothes i can keep in total counting all the equipped items together is 8 and the items removed are always randomized no matter the order or which Kobold is wearing them

**Comment by naelstrof** [comment]
I couldn't replicate this issue. 
Keep in mind that old saves have had all penis equipment removed, the save loader gets confused and will replace them with default dicks and pseudo-random equipment.

Not easy to maintain full backwards compatibility with how different things are structured now.

**Comment by OfficialMonsterCrush** [comment]
i was playing on new saves made for the beta branch and all the equipables were placed on female kobolds, ill keep messing around with it to see if its a issue with the amount of stuff spawned in but I dont think that was fully the reason it was happening
