### ISSUE TITLE
Weight gain regents not affecting blendshapes

### ISSUE THREAD

**Issue by imsuckus** [naelstrof/KoboldKare#206]
Consuming anything that increases kobold weight will not visibly change weight. Genes don't seem to be changed as children of the fed kobold are also unaffected.

**Comment by naelstrof** [comment]
Cannot reproduce as of [5c8850b](https://github.com/naelstrof/KoboldKare/commit/5c8850bbf256c05909afefb81e6cbd41cf51b917)

**Comment by Godeken** [comment]
Id like to understand too... logic is setup if energy = max, turn energy into fat... i made many fat Kobs last night so i dont see an issue here.

@imsuckus can you share a clip of this?
