### ISSUE TITLE
Trapped in Game 

### ISSUE THREAD

**Issue by OfficialMonsterCrush** [naelstrof/KoboldKare#209]
When joining public servers in the beta build there are occasional times where you cant click on any of the escape options or settings making it to where you can only quit via alt f4 or forcefully closing the game

**Comment by naelstrof** [comment]
I haven't been able to replicate this yet, I believe it exists though, lots of recent changes has messed with how the UI interfaces with the player controls.

**Comment by naelstrof** [comment]
I found if you pressed ESC at the wrong time when trying to save, that it would lock up the interface. After my change I couldn't lock up the interface anymore. There could be other situations where it could get locked up though (if popups were shown and couldn't be cleared for example.)

Hopefully this fixes it well enough though.
