### ISSUE TITLE
Hip controls no longer lock camera

### ISSUE THREAD

**Issue by PonemanTL** [naelstrof/KoboldKare#216]
Running on Linux.
 Prior to the recent rework, holding the hip-control button would lock your camera forward while you moved your character's hips. Now it no longer does, so if you thrust back and forth, you also throw the camera violently up and down. Which is fun if you like getting motion sickness, I guess. I'm not a fan though.

**Comment by naelstrof** [comment]
Do you have replication steps? I cannot replicate the issue.

Do you have custom bindings?

**Comment by PonemanTL** [comment]
Oh yes, I've bound it to a mouse button. (I have "forward/back" buttons on the side of my mouse, and bound each to something) I'll try to see about testing default bindings tonight.

**Comment by naelstrof** [comment]
Oh good to know, I can try to replicate the bug now that I know.
