### ISSUE TITLE
in multiplayer as client you can't interact with anything inside pause/esc menu

### ISSUE THREAD

**Issue by CanInBad** [naelstrof/KoboldKare#217]
On latest beta (631_716EDCBC) multiplayer, you can't interact with anything in the menu if you join a server
![2023-03-16 21_14_48-KoboldKare](https://user-images.githubusercontent.com/73659199/225645183-7cef77a7-c2af-46ac-b7c7-52b5834e3fcc.png)

**Comment by Godeken** [comment]
I think this has been rectified by @naelstrof already, he just recently rebuilt the UI.

**Comment by CanInBad** [comment]
ight closing this then

**Comment by naelstrof** [comment]
Yeah specifically commit 1f087ff83260f3d1f4054d9765e94d7aa5d2da64 should fix it, probably still needs more testing but as far as I can tell it's fixed.
