### ISSUE TITLE
faulty asset (and probably build issues)

### ISSUE THREAD

**Issue by JustONOFF** [naelstrof/KoboldKare#218]
Good day naelstrof!

Currently I'm trying to build the game from source but came by a few errors in the process.
- First off, the first few times when I imported the project into Unity, I got some error messages about some assets missing. I figuered out that the problem PROBABLY came from blender since I didn't find any Variable for blender in my PATH. I then specificaly downloaded the 2.93 version and added the PATH manually to my system variables, since Windows didn't want to do it by itself. That apparently fixed these issues.
- But now when I'm trying to build the adressables, I get an instant build error like seen here:
![image](https://user-images.githubusercontent.com/84670227/225895644-52126c3a-3189-47f0-9a36-2d93db4ba651.png)

I also get a error message saying that the file type for WinePress.blend in 'Assets/KoboldKare/Models/WinePress.blend' couldn't be recognized. So I opened the .blend file in blender and saw, that it's just the default scene from blender.
Am i doing something wrong on my side or is this asset as mentioned faulty? I even tried downloading this .blend file directly from this GitHub page but the results were the same.

Would be glad if you could take a look at it and say what I am doing wrong

**Comment by naelstrof** [comment]
You'll need to update blender then reimport all the models. I'm using version 3.4 of blender.

**Comment by JustONOFF** [comment]
Oh yeah installing a newer version of blender actually fixed that problem! I was now able to build the game myself, so thanks for the advise
