### ISSUE TITLE
Import/Export Kobold Model

### ISSUE THREAD

**Issue by JustONOFF** [naelstrof/KoboldKare#220]
Hi again

My next goal is to import the kobold model to alter it in blender and the use it in the game. But I have some troubles importinbg/exporting it in unity and it gives me this warning:
![image](https://user-images.githubusercontent.com/84670227/227391996-4b39c9bb-301c-488b-bbc7-b57833c66f2d.png)

I haven't altered anything on the model (yet), just tried to import the .fbx file into blender then export it back into unity but I don't really know what settings i have to use, to get the exporting correct.

when i try to start ther game, the model is all out of proportions and seems gigantic:
![image](https://user-images.githubusercontent.com/84670227/227392389-1bc30cc2-0f5a-4ee4-a77a-0050b2fa83d0.png)
[nsfw image](https://user-images.githubusercontent.com/84670227/227392674-4209087e-8e19-4174-a2f6-865420e7a4da.png)
(You can ignore the lack of color on the kobold, I fiddled around a bit with the export options in blender and it usually has the textures loaded :) )

So yeah if anyone knows how to do it right, it would be very helpful to set me in the right direction

**Comment by naelstrof** [comment]
Ah yeah, I'm still working on some docs for that, but you're in luck for this.

https://wiki.koboldkare.com/index.php/Getting_started_with_Character_Modding#Select_both_the_Body_and_Armature,_then_export_them_together_as_an_FBX_with_the_following_settings:

You'll want to follow some of the instructions here for exporting, specifically about the FBX settings.
Namely you'll need to make sure that `Apply Scalings` is set to `FBX Units Scale`, and that `Add Leaf bones` is turned off.

For importing, you can actually find the original kobold source blend file here: 
https://github.com/naelstrof/KoboldKare/tree/master/SmallSources

I hope that helps!

**Comment by JustONOFF** [comment]
Thanks for the reply, it helped a lot!

I could successfully import the model in unity and it worked flawlessly.

For testing purposes I enlarged the kobold's head to comically large proportions to see if that also works as flawlessly as directly importing it without any alterations. but wierdly when i imported the model and startet the game, it still had the default model, despite the applied alterations in the unity preview. I modified the Kobold.fbx file in Assets/KoboldCare/Models by the way, because I assume that's the appropriate model for the player and the kobolds in the game. Do you know what I have to do to see my changes in the actual game? I thought just changing the model itself would suffice but i guess that's not right

By the way I really appreciate your relatively fast replies and the active support  you give on this github project, keep it up!

**Comment by JustONOFF** [comment]
Actually nevermind, I finally figured a way to solve the problem after countless hours

First I thought, that you just have to change the 'Kobold' model in /Models but after some researching and experimenting, I found out it's actually stored in a prefab.

With a bit of digging in the editor i found out, that the default kobold is not stored in /prefabs like i thought, but is stored in /NetworkedPrefabs.

With a ton of experimenting I found out, that you have to change the mesh in the skinned mesh renderer, when you open the mentioned prefab and select 'Body' in the hierarchy. You fcan find a line with 'Mesh' written on it and there you can select the desired mesh for your kobold.

So for anyone who also wants a custom mesh for their default kobold, I described it very roughly to follow. You just have to know a bit what you are doing and you will be fine. Just make sure you export your model in blender the properly or else you will have a bad time.

**Comment by naelstrof** [comment]
Oh yeah, sorry! That's because there's some mesh data baked in for procedural mesh deformation. The procedural deformation monobehavior has a bake button that replaces the prefab mesh. 

I'll cover this on the wiki once I finish up this ragdoll tech.
