### ISSUE TITLE
Game crashing a lot, texts disappearing

### ISSUE THREAD

**Issue by flaiming** [naelstrof/KoboldKare#221]
Hi, I have laptop lenovo L490 with Core i7 8th gen and  integrated graphics, win 11. In order to actually be able to play the game I had to add `-force-vulkan` parameter, otherwise the game will crash right after the menu. 

I have several issues with the game:
1. The game is overall stable, but it will crash every time I do more of milking for quest of getting fat kobold. When I do a few milks, it will just crash. I even got the error message once, see screenshot.
2. When some kobold is cumming/milking, the frame rate drops significantly. Lowering the screen resolution does not help.
3. When I load the saved game, all texts from menu and subsections will disappear. Even the money and star counter in the game.
4. The game is in Czech, probably because I have Windows in Czech. I would like the game to be in english, but I did not find any option or config how to do that. 

is there a way how to fix at least some of these issues?
 
![Screenshot 2023-03-25 221640](https://user-images.githubusercontent.com/1169782/227743835-7a69b097-1585-4ecc-9b51-1111e374b0d9.png)

**Comment by naelstrof** [comment]
Have you tried running the game with `-force-vulkan` or `-force-glcore` as a launch parameter? Some integrated hardware can't run the directX mode properly.

**Comment by naelstrof** [comment]
There's also a language setting under the gameplay options, which would allow you to play the game in English.

**Comment by flaiming** [comment]
@naelstrof Thanks, switching from `-force-vulkan` just to `-force-glcore` seems to be helping, it did not crash after 10 minutes of milking :) Will keep testing when I have the time.

Also thanks for guiding me how to switch the language - it was really there, I don't know how I missed it. Maybe because Gameplay seems to be selected by default when you go to settings and there is nothing at the right side of screen, so I expected that there are no options for Gameplay.

I will close this issue for now.
