### ISSUE TITLE
Bunch of prefab GUID errors when opening this repo in Unity 2021.3.19f1

### ISSUE THREAD

**Issue by TearOfTheStar** [naelstrof/KoboldKare#244]
Basically a ton of assets can't load properly due to "missing" prefabs. After a bit of digging it seems like most if not all missing prefab GUIDs are for .blend files. 

Were all assets and their .meta files committed properly? Or am i missing something?

I did check this repo and in my cloned one, they are 1 to 1. Blender is installed thru .msi files, several versions of it are present.

All i did was clone and then open with Unity (had to dl needed version).

For example; 
"Prefab instance problem: Pachinko (Missing Prefab with guid: d7c11eef3e2f3444c8dbbc4147205458)". 

This GUID is set for Pachinko.blend in Pachinko.blend.meta.

I think it leads to several errors that count up continuously:

![kkerrors](https://user-images.githubusercontent.com/5261740/231160054-c47a5d97-8f2c-45fb-8b60-43143e940407.png)

**Comment by naelstrof** [comment]
This can happen if you load the project when blender is not on your PATH. Env variables are cached and reused from Unity Hub. Meaning you cannot install new programs after you've launched it. You most likely need to restart your computer and reimport the entire project.

**Comment by Godeken** [comment]
Same happened to me but followed tips from Naelstrof and all working again...

**Comment by naelstrof** [comment]
I installed Blender 3.5, and was able to import the blends just fine.

![image](https://user-images.githubusercontent.com/1131571/231610571-b9e075c2-5680-4e75-9f40-0a89805cffc5.png)

I did get a warning on import though: `Importer(FBXImporter) generated inconsistent result for asset(guid:f64225a371e667f4487b8cc76d8e421b) "Assets/KoboldKare/Models/ConstructionHat.blend"`

Looking that up online says that the assets should work fine regardless, everything appears to be working normally.

You may need to verify that Blender 3.5 is indeed on your PATH, and that you have no other Blender versions on your computer.

The windows package manager is very good at maintaining a single, up-to-date version of Blender and I highly recommend using it.
