### ISSUE TITLE
Suggestion: Add toggle-able single/multi-grab modes.

### ISSUE THREAD

**Issue by ppaawwll** [naelstrof/KoboldKare#260]
Playing as a kobold with upgraded carry capacity is wonderful for carrying many items from place to place, but makes trying to use machines (such as the milking table) very frustrating, as trying to place a kobold near it while another kobold is already there just grabs the kobold on the table as well, and you have to finagle the other kobold to work the machine.

A toggle between single-grab and multi-grab with the normal left click would be a good quality-of life change imo.

**Comment by ppaawwll** [comment]
Thinking about it, I could try adding that feature myself in a forked branch, but I do not know the specifics of when it's okay to fork it and make changes other than after a moderator responds.

**Comment by naelstrof** [comment]
yeah I'd love that, I only have two conditions:

1. It needs to work on the Steam Deck (can't simply add a new bind, a combo bind would work great).
2. If you need localization, poke me so I can add it to the source spread sheet-- as it's imported from google sheets.

**Comment by ppaawwll** [comment]
Was planning on having the bind having something to do with tapping shift or shift+something anyway so.
Also, will do if I need to!

**Comment by ppaawwll** [comment]
I couldn't think of a shift+button combination that I felt worked so I made it switch by tapping shift quickly.
I managed to get it working and using machines feels so much better now.
I added a UI panel on the left with the control, which also has the only piece of text I've added, "Tap."
How would one integrate that into the localization system this game has?

**Comment by ppaawwll** [comment]
![image](https://user-images.githubusercontent.com/78707934/233870573-ddb2f2a4-44cf-4745-9856-0ab4bd905261.png)
![image](https://user-images.githubusercontent.com/78707934/233870582-8d52fdac-4381-46f8-9022-082c70e2cfb5.png)
Here's what it looks like as it currently is.

**Comment by ppaawwll** [comment]
Created a pull request if you want to look at it first.;

**Comment by naelstrof** [comment]
sweet, I'm going to check it out sometime tomorrow. Got a lot of critical bugs that I'm working on first.
