### ISSUE TITLE
Thai doesn't have a font fallback.

### ISSUE THREAD

**Issue by naelstrof** [naelstrof/KoboldKare#270]
All thai text shows up as squares at the moment.

**Comment by CanInBad** [comment]
Suggestion for fonts

1. https://fonts.google.com/specimen/K2D
2. https://fonts.google.com/specimen/Sarabun
3. https://fonts.google.com/specimen/Kanit/
4. https://fonts.google.com/noto/specimen/Noto+Sans+Thai/
