### ISSUE TITLE
No gameplay

### ISSUE THREAD

**Issue by Aydenthguy** [naelstrof/KoboldKare#274]
[20230406_133004](https://user-images.githubusercontent.com/132724131/236591839-608da740-d5ad-4f3f-838c-4b1a8f7f6745.jpg)
So everytime i open the game and start a new world since the workshop integration, i get this. The hud comes up and works just fine but the game doesn't load in. I know it is not my graphics card is not the issue because i play games that are more demanding then this and they run just fine.

**Comment by naelstrof** [comment]
Are you loading a save or are you trying a new game?

I'm going to need your Player.log, you can find it here: `C:\Users\<username>\AppData\LocalLow\Naelstrof\KoboldKare`

**Comment by naelstrof** [comment]
Closing due to lack of interaction. Make another issue if you still have a problem.
