### ISSUE TITLE
Game suggestion

### ISSUE THREAD

**Issue by livoniatim** [naelstrof/KoboldKare#30]
The oviposition is cool, but it doesn't work quite well. Every time I get multiple eggs in a kobold the get a huge spike for a belly and the eggs immediately fall out.
What if you change the oviposition from physically to imaginary.
The egg is a physical object until it is ingested orally, anally, or vaginally. Then the egg becomes a number that makes the kobold look pregnant until you use the "shift hand" to remove an egg from the kobold. So you can still grab kobolds, you can put many eggs in a kobold without causing the kobold to get a weird jagged pregnant look, and be able to move the kobolds around with eggs in them without them falling out.
Or when a kobold gets pregnant with eggs through ingestion or inseminations just put them in the heating hut for them to start laying eggs. If they are not in the hut then don't lay eggs, maybe? (Heating hut is that small wood house that was shown for cooking stuff)

**Comment by naelstrof** [comment]
This is a wonderful idea, and virtually keeping track of what's inside a kobold is a great way to help author shapes. However I'm hoping that the changes I've made to the game has made this largely irrelevant. Kobolds now turn all egg inside them into one very large egg via the egg laying station.

This was done more for performance considerations than for gameplay or fetish related ones. I hope that's okay for now.
