### ISSUE TITLE
[BUG] Ice upgrade spawns a lot of ice after loading a save

### ISSUE THREAD

**Issue by ghj0sh** [naelstrof/KoboldKare#31]
Dont know if this bug is known or not, but there's a bug after loading a save game where it spawns a bunch of ice.  If I had to guess, it's spawning in every piece of ice that you got from previous days, so if you get the ice upgrade and save after 50 in-game days pass, it'll spawn 50 pieces of ice from the fridge.

Pretty easy to replicate.  All you gotta do is buy the ice upgrade, pass a few days, save, and reload the save.

Here's a video of the problem if you need it:
https://mega.nz/file/g64ixJAJ#fuapvjNwATKwRItVfvGOt5ZgEpeRngbLFRQ6kn3DPz8

**Comment by naelstrof** [comment]
Good find, it took me a long time to realize what was causing it, should no longer be an issue!
