### ISSUE TITLE
How do I run this?

### ISSUE THREAD

**Issue by Ericj3342** [naelstrof/KoboldKare#314]
@naelstrof How do I run/install this?

**Comment by cocorico8** [comment]
you need to compile it on unity 2021.3.19f1

**Comment by CanInBad** [comment]
[💀](https://github.com/naelstrof/KoboldKare/blob/master/CONTRIBUTING.md#installing-and-editing-koboldkare)

**Comment by cocorico8** [comment]
ok i wanted to compile it but i don't understand the addressable

**Comment by naelstrof** [comment]
There's no such thing as installing. If you're asking how to build, you can find build instructions here: https://github.com/naelstrof/KoboldKare/blob/master/CONTRIBUTING.md#building

You do not need to build in order to test the game within the unity editor.
