### ISSUE TITLE
[BUG] Cant change resolution without using keyboard

### ISSUE THREAD

**Issue by ghj0sh** [naelstrof/KoboldKare#32]
Title is self-explanatory.  Looks fine in the unity editor, but when you try changing the resolution in the actual game, you can't change it without using the arrow keys and enter.

Video:
https://mega.nz/file/pzgQ2SBJ#p9cHR2R_dftAk8TvskZ5EH9NpoqaVFvxw0nCKhtZG6U

**Comment by naelstrof** [comment]
Oh shoot, I missed this issue. I don't think this is an issue anymore, and if it is-- please make another request!
