### ISSUE TITLE
Fixing this blank error

### ISSUE THREAD

**Issue by floppydiskette** [naelstrof/KoboldKare#33]
Attempting to work on the source code using Unity, however I consistently get this blank compiler error whenever I try to play/build the game (either in the editor player or by building). As this error gives absolutely no information on its origin, I was wondering if anyone else had encountered this error and thus knew anything more about it
<br><br>
![a blank unity error](https://i.imgur.com/9iA3Z0d.png)
<br><br>
Some information that might be helpful:

- Attempting build on OpenSuse Tumbleweed (Linux x86_64)
- Using Unity version 2020.3.20f1 with the Vulkan renderer

**Comment by naelstrof** [comment]
No other errors? Do you have blender installed (and it's within your PATH)?

**Comment by floppydiskette** [comment]
I have checked and yes blender is in my PATH, one thing I didn't notice however is that upon restarting Unity, I've gotten these two other errors. No additional information is provided when clicking on them.

![two errors stating "Unknown platform 3 in GetRenderList"](https://i.imgur.com/DwDkEju.png)

**Comment by Electric-Cat** [comment]
> I have checked and yes blender is in my PATH, one thing I didn't notice however is that upon restarting Unity, I've gotten these two other errors. No additional information is provided when clicking on them.
> 
> ![two errors stating "Unknown platform 3 in GetRenderList"](https://camo.githubusercontent.com/a7cb48c49f0962eda90eb7ee7d39f294ad05d65e43fad78bbc1661c843150fb4/68747470733a2f2f692e696d6775722e636f6d2f4477446b456a752e706e67)

From what I found on the internet, the error "Unknown platform 3 GetRenderList" is an error for those who downloaded the "VRChat SDK", in principle it doesn't change anything in the game, but this is what I found with the little information available...

About the other error, I don't know much about it, maybe this will help: 
( https://forum.unity.com/threads/unity-not-showing-compile-errors-anymore.183776/ )

Sorry about my English.

**Comment by naelstrof** [comment]
That's a really good find, and yeah these errors don't affect runtime or compile time code. So I'm going to close this issue for now.
