### ISSUE TITLE
Suggestion: Vulva types and modifiers

### ISSUE THREAD

**Issue by SunnyOpossum** [naelstrof/KoboldKare#34]
Players should be able to customize and change the size of vulvas like you can with penises.
Was pretty disappointed to find no customization for them.
A pinned message in the official discord said to post feature requests here.
Besides that the game is very enjoyable so far! Keep up the great work! Very excited for the game's future! :)

**Comment by naelstrof** [comment]
Thank you! Sorry it took me so long to respond. I sometimes read these things in the morning, realize I can't do anything about it, then forget everything about it.

Yeah I have no plans for vulva customization, this is something that might be very fun to add via mod for custom characters. Look out for the modding update if I ever make it that far.
