### ISSUE TITLE
my KoboldKare game is all messed up. a bug

### ISSUE THREAD

**Issue by jonminecraft54** [naelstrof/KoboldKare#346]
my KoboldKare hentai game is all messed up. The GUI for starting a new game is broken and the textures are all messed up too. I don't know why, I even updated my graphics. i did do wipe the game and i did a clean install of the game it still broken 

![vid](https://github.com/naelstrof/KoboldKare/assets/155730083/a2a2d2a1-80dc-488d-9a8d-69c3dbf990a3)

**Comment by naelstrof** [comment]
Misconfigured mods can cause this. Try uninstalling them one at a time to find the culprit mod. It can simply be a combination of mods as well.

**Comment by jonminecraft54** [comment]
I did turned off the mods. still The GUI for starting a new game is broken I don't know why, 
![Uploading Captu534534re.PNG…]()

**Comment by jonminecraft54** [comment]
<img width="480" alt="Captu534534re" src="https://github.com/naelstrof/KoboldKare/assets/155730083/f002ec75-6ccc-44eb-b781-aff3b493bd76"> I turned off the mods but the new game start button is still acting up for some reason. It's so annoying, I have no idea what's going on.

**Comment by jonminecraft54** [comment]
can you fix it? that new game start button is still acting up with the update to

**Comment by jonminecraft54** [comment]
I deleted the game and reinstalled it, but the new game start button is still acting weird after the update.

**Comment by naelstrof** [comment]
Workshop mods aren't installed with the game, mods can either be found here: `C:\Users\<username>\AppData\LocalLow\Naelstrof\KoboldKare\mods`
Or in special workshop folders by Steam.

I cannot fix this bug. You'll have to uninstall your mods.

**Comment by jonminecraft54** [comment]
i did delete it folder it is in

**Comment by jonminecraft54** [comment]
i fix it btw

**Comment by jonminecraft54** [comment]
i did fix it dw
