### ISSUE TITLE
Feature: Sculpt Cheat Command

### ISSUE THREAD

**Issue by woemwoemwoemwoem** [naelstrof/KoboldKare#347]
Hello,

I just created a cheat command called Sculpt that allows the user to change the genes for dicks, balls, boobs, and height of the kobolds.

I'd like to create a PR to add this to the project, if you'll allow me to. The changes are quite simple.

According to the Contribution Guidelines, I'm creating this issue first before creating the PR, to be validated by a moderator.

My logic for this cheat is that there may be maps that don't have the necessary reagents to modify a kobold's attributes, as well as people who just want to have fun messing with proportions (that's what cheats are for, after all)

Thank you for your time!

**Comment by naelstrof** [comment]
Sounds like a great idea! Go ahead and make a PR.

**Comment by LittleCodingFox** [comment]
Taken care of by #348 ! Thanks a lot!

**Comment by woemwoemwoemwoem** [comment]
Taken care of by #348  ! Thanks a lot!
