### ISSUE TITLE
When doing "build" the texts and icons do not appear.

### ISSUE THREAD

**Issue by Electric-Cat** [naelstrof/KoboldKare#40]
I tried to research before asking here, I didn't want to be annoying, but I didn't find what the cause of the problem would be, it might be something very simple but I really don't know, thanks for your time.

![photo_2022-09-22_12-32-59](https://user-images.githubusercontent.com/60434386/191736005-5ae9ed47-defe-486c-b650-3d9480f790de.jpg)
![photo_2022-09-22_12-33-02](https://user-images.githubusercontent.com/60434386/191736023-d0d314ec-dd1d-48de-b0a7-7784c40bffbf.jpg)
![photo_2022-09-22_12-33-06](https://user-images.githubusercontent.com/60434386/191736035-eea84748-1181-4aa4-9e11-afe85ae82cbc.jpg)

Sorry my english.

**Comment by Adorabold-Kobold** [comment]
I have the same issue and i looked into it a little and i think it might be something about localization/language?

I havent found a fix at the moment.

**Comment by naelstrof** [comment]
You just have to build the addressables! There's a special build addressables menu under the Window tab at the top of unity. You may need to look up a tutorial for it.

**Comment by naelstrof** [comment]
You can find it here:
![image](https://user-images.githubusercontent.com/1131571/208358585-efd436a8-2735-4db4-b212-207bde42b0d9.png)
Window->Asset Management->Addressables->Groups

Then hit 
![image](https://user-images.githubusercontent.com/1131571/208358698-c5f68912-2940-45a0-9ca6-e3a505932f94.png)
Build->New Build->Default Build Script

Then your builds should turn out okay. I'm going to close this issue now!
