### ISSUE TITLE
Perfect Kobold Objective - Potentially unintended behaviour

### ISSUE THREAD

**Issue by Shurutsue** [naelstrof/KoboldKare#42]
https://github.com/naelstrof/KoboldKare/blob/d9ac88ff573622aa74bc01c4b8bd7b497889602e/Assets/KoboldKare/Scripts/Objectives/DeliverThePerfectKobold.cs#L42
Intended to be `bellySize` and not `metabolizeCapacitySize`?
I assume, since it expects a Kobold to be certain generations in, that it might actually be the wrong gene referenced.

**Comment by naelstrof** [comment]
Oh yeah, good find. You're correct. Though I believe I should just also add metabolizeCapacitySize. It would make sense that a dragon would want a kobold that could hold everything that they could give.
