### ISSUE TITLE
Suggestion: Toggle for Y-axis look inversion

### ISSUE THREAD

**Issue by xetem** [naelstrof/KoboldKare#45]
I know, I know, y-axis inversion isn't the most used or sought after feature, but weirdos like myself would greatly appreciate having our mouse moving doing what some of us have put thousands of hours into muscle memory.

I noticed here https://github.com/naelstrof/KoboldKare/issues/44#issuecomment-1355854861 that there are config file re-bindings available and I wonder if something similar is already available as a workaround for inverting the mouse y-axis.

**Comment by naelstrof** [comment]
Oh!! Sorry there isn't any way to invert the mouse right now. I could very easily add it though! 

When I add the feature I'll close this issue.
