### ISSUE TITLE
[Bug] Game won't render anymore

### ISSUE THREAD

**Issue by xetem** [naelstrof/KoboldKare#47]
So the game had a strange crash, not to worry I'll just launch it again. Well now the game only launches like this and won't let me resize or maximize the window.

![image](https://user-images.githubusercontent.com/91496021/208369288-ee862539-28fa-45b1-aea5-f6a39d59b0ab.png)

The grey is my desktop wallpaper.

I've tried reinstalling and clearing everything KoboldKare related out of appdata, but no change in behavior.

OS: Windows 10 21H2 [19044.2364]

**Comment by naelstrof** [comment]
Ah yeah, this is apparently something that can happen to any unity game that has its resolution set to 0x0 and saved.

To fix it you'll need to open regedit and delete all the keys found at `Computer\HKEY_CURRENT_USER\Software\Naelstrof\KoboldKare`

Specifically these two keys are responsible for the screen resolution, so you might get away with just deleting these two:
![image](https://user-images.githubusercontent.com/1131571/208375460-983d99b4-673a-4033-a271-c3ea8e8e4409.png)


I'm not exactly sure how this happens-- the only resolutions my app is setting is the ones reported directly from Unity. The related code can be found here:

https://github.com/naelstrof/UnityScriptableSettings/blob/main/Assets/UnityScriptableSettings/Scripts/SettingTemplates/SettingResolution.cs

I'm not quite sure how to fix this bug without doing hacky things like just forcing the window to be at LEAST 100x100 or something. Sorry!

**Comment by naelstrof** [comment]
Oh wait. I am totally just reading `Screen.currentresolution` and writing it back to the registry. It's possible that if the screen is minimized, `currentresolution` might report 0x0. 

It might take me a while to fix this bug, as I'm fairly sure that I put that in because it *wasn't* saving the resolution automatically. Lots of testing needed.

**Comment by xetem** [comment]
So I found with some help from a friend that `alt+enter` will change the window type between one of the windowed and fullscreen mode. So as a hacky fix to get anyone else who encounters this playing again, `alt+enter` will help.
