### ISSUE TITLE
Milker Changers

### ISSUE THREAD

**Issue by DonglyKnog** [naelstrof/KoboldKare#5]
Couple ideas for improving the milker, cause it can be a lil temperamental to work with right now.

Idea 1: make the milker turn "On and off" when you interact with it (press E). When it is on, it will actively try to find something to latch on to. When it is off, it will just flop down and not do anything.

Idea 2: maybe make the milker a "farm expansion/upgrade" Instead of it being something you buy and bring back yourself. It could be auto installed when bought, and placed in a dedicated milking are on the farm where it is stationary. With this idea you could possibly work in an upgrade system in the future, such as more milkers installed, Storage tanks, or Efficiency.

**Comment by naelstrof** [comment]
It might work better as a farm upgrade, the idea is that if someone was only interested in that kind of stuff, that they can focus their entire gameplay upon it.
Because of that I might keep it a purchasable, it does need to be easier to place. Perhaps I should turn it into a deployable?

**Comment by DonglyKnog** [comment]
deployable would be a good idea!

**Comment by HubullKing** [comment]
I would like to build off of DonglyKnig’s proposal for installed Milkers and Storage Tanks by citing the video on Patreon titled “Boob/Belly/??? Grow Mechanics”. I think an additional upgrade to the farm built off the former suggestions by DonglyKnog should be the spout in the video spraying from the upper floor/ roof of the farm house. I think this could also work as a possible upgrade to the watering can similarly proposed by moresmallerbear.
