### ISSUE TITLE
Listing bugs I've come across (some might be repeats or fixed) and small QOL suggestions.

### ISSUE THREAD

**Issue by tarunio** [naelstrof/KoboldKare#53]
_Understandable If it takes time to get these fixed/implemented or not implemented_

**Bugs**
1. In option menu if you use scroll wheel on sections like resolution you get sent to the most end of the options instead of small intervals.
2. Camera FOV option has decimals instead of being like 'target framerate' slider using whole numbers.
3. Doors cost 0 stars on save/load
![image](https://user-images.githubusercontent.com/60945778/208600356-64e75d49-43f7-44aa-9b20-f674d76c70d2.png)
4. The common "explosions" reappearing on save/load.
5. Adding a limit to how many bracelets and tailbags you can wear.

**Small Suggestions**
1. Seeds for missing foods (banana, maybe mushroom).
2. Bigger egg laying area for big kobolds so eggs don't fall in the void.

**Big Suggestions**
1. BDSM place or stations like how the inflator poses the bold.
2. Another area on the map with farming tiles like putting it in the cavern near the tent.
4. Free cam posing (might have issues in itself so, eh)
6. Invisible walls and roof so you don't accidently respawn out of bounds.
7. Shift grab penis and breast (mentioned on discord).

Might make a part 2 or edit this if I come across more Bugs/Ideas.

**Comment by naelstrof** [comment]
In the future it'd be nice to keep bugs in separate issues so I can individually track them! I'm going to close this issue as I've fixed one of the bugs. If you want the others to be properly tracked, please make individual issues for them!

**Comment by tarunio** [comment]
ok.
