### ISSUE TITLE
Linux mousewheel either doesn't work, or is read differently compared to other platforms.

### ISSUE THREAD

**Issue by naelstrof** [naelstrof/KoboldKare#54]
Not sure what the cause is, I'm guessing there's an InputSystem bug for Unity, worried that I'll need to make platform specific hacks to fix it.

**Comment by Heartless68** [comment]
Could potentially be related to: https://issuetracker.unity3d.com/issues/linux-editor-ignores-mouse-scroll-wheel-input-when-the-cursor-is-locked-on-the-new-input-system

**Comment by naelstrof** [comment]
Oh yup, that must be the issue. I can see in their "known issues" of the newest LTS a "URP Memory Leak", and "Visual FX graph opaque node doesn't write to depth". https://unity.com/releases/editor/whats-new/2021.3.16

Which would make KoboldKare an unusable project, I'll wait for 2021.3.17 and see if the known issues are a little bit less drastic.

**Comment by PonemanTL** [comment]
Fixed in current master, with Unity 20121.3.19f1.
