### ISSUE TITLE
Free Rock Clearing on Loading Save

### ISSUE THREAD

**Issue by ocarina0001** [naelstrof/KoboldKare#59]
https://youtu.be/MScylZjzsf8

I'm not 100% sure what causes it, but if I had to guess maybe an explosion is being triggered from a bomb I used a while ago and isn't deleted properly?

**Comment by Godeken** [comment]
Did you have any kobolds that were pinned up before this happened?

**Comment by naelstrof** [comment]
I believe this is because explosions take a few seconds to really remove themselves, and get "saved" if you save while they're still invisible.
