### ISSUE TITLE
Suggestion: De-growth mushroom recipe.

### ISSUE THREAD

**Issue by tarunio** [naelstrof/KoboldKare#65]
Mushroom + Eggplant = Penis shrink

![image](https://user-images.githubusercontent.com/60945778/209253433-409a4f11-bb34-4f45-bbd8-fbaf0f324e3c.png)

Mushroom + Pinapple = Balls shrink

![image](https://user-images.githubusercontent.com/60945778/209253828-4657c639-1644-4f00-b591-0a3a55a420e3.png)

Mushroom + Melon = Boobs shrink

![image](https://user-images.githubusercontent.com/60945778/209254216-f8710dc4-767f-4e7c-8bcd-aa5ec1f0e31f.png)

**Comment by naelstrof** [comment]
Yeah I actually love this idea, and it's not too terribly difficult to implement. I'll look into it.

**Comment by naelstrof** [comment]
Implemented as of 4bb2effe491339bdd8217b52ebe017c0a835b357
