### ISSUE TITLE
Suggestion: Create a kill box under the Map

### ISSUE THREAD

**Issue by Godeken** [naelstrof/KoboldKare#66]
I have been looking into it, had a session that ran about 12 hours and had Kobolds making tons of hearts, etc... got rid of the hearts (took almost an hour) but noticed a large frame drop... I was wondering, if things fall through the floor like Eggs and Hearts, do they get destroyed below the map, or do they just fall forever?

**Comment by naelstrof** [comment]
They do actually already. I still need to address the fact that the game will tank when you play for 12 hours, but items that fall out of the map do get cleaned up. It's smart too-- there's a lazy checker that iterates through all items in the game to keep them in the "play area".

**Comment by naelstrof** [comment]
See [PlayAreaEnforcer.cs](https://github.com/naelstrof/KoboldKare/blob/master/Assets/KoboldKare/Scripts/PlayAreaEnforcer.cs)

Most items attempt to subscribe to it, if you can find an object that can move and doesn't subscribe to the PlayAreaEnforcer, that'd be a bug!

**Comment by Godeken** [comment]
Teach me Sensei! I must remember that for my own game one day
