### ISSUE TITLE
Turning on the dick breaks the main character Kobold

### ISSUE THREAD

**Issue by mja00** [naelstrof/KoboldKare#69]
I noticed once the dick is enabled nothing happens and you're then unable to modify any of the other settings for the kobold. Once turned off it stops breaking it. It looks like the issue is the inflatable is never initialized so it returns an error. 

```
UnityException: Inflatable wasn't initialized 
Naelstrof.Inflatable.Inflatable.SetSize (System.Single newSize, UnityEngine.MonoBehaviour tweener) (at Packages/com.naelstrof.inflatable/Inflatable.cs:45)
Kobold.Update () (at Assets/KoboldKare/Scripts/Kobold.cs:441)
```

**Comment by naelstrof** [comment]
What version of the game are you on? I cannot replicate this issue.

And you mean just booting up the game and just enabling/disabling the dick within the Multiplayer options right?

**Comment by mja00** [comment]
I was attempting to build the game from source but it looks like it might just be a bug when building the game from source and I was most likely just building it wrong as the Steam copy of the game appears to work fine. Apologies.

**Comment by naelstrof** [comment]
Yeah no problem! Check out [Compiling.md](https://github.com/naelstrof/KoboldKare/blob/master/COMPILING.md)

The instructions there are very important, chances are you didn't have `blender.exe` in your path when you first imported the project. You may need to install blender and then reimport all the assets.
