### ISSUE TITLE
Building for Apple Silicon Mac

### ISSUE THREAD

**Issue by shelbyKiraM** [naelstrof/KoboldKare#74]
A lot of issues when I open the project; I can compile and test whatever for getting this to work, but I always get errors for things intended to run on x86_64, e.g.:

```
Plugins: Couldn't open /Users/user/github/KoboldKare/Assets/Plugins/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon, error:
dlopen(/Users/user/github/KoboldKare/Assets/Plugins/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon, 0x0002): tried:
'/Users/user/github/KoboldKare/Assets/Plugins/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon'
(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')),

'/System/Volumes/Preboot/Cryptexes/OS/Users/user/github/KoboldKare/Assets/Plugins/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon' (no such file),
'/Users/user/github/KoboldKare/Assets/Plugins/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon'
(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

I really wanna play... but at family holiday get-together right now so none of my Win/Lin machines. Lemme know what I can do! 😁

**Comment by naelstrof** [comment]
Oh thank you! I don't think I use the photon audio plugin whatsoever. It should be safe to remove it.

**Comment by naelstrof** [comment]
I'm not exactly sure what needs to be done though. I'm unsure if I can get m1 apple chips to work at all in a short time span, got the exact opposite problem of holidays and only being surrounded by x86_64 hardware.

**Comment by shelbyKiraM** [comment]
No prob, thx! I can build for you if you wanna push changes to the repo, but maybe after the big family day 😆💖🥰🐾🍜

**Comment by shelbyKiraM** [comment]
Uh now there's a bunch missing prefabs? Can I bring 'em in from the game on steam? I'm trying to get it so I can play on my M1 still even tho I'm home and could just pop it on my PC. Sigh

**Comment by shelbyKiraM** [comment]
I got it to run in CrossPlay but I still haven't bought that sooo

**Comment by naelstrof** [comment]
Ah yeah whoops, I shouldn't have closed this, let me reopen.

**Comment by naelstrof** [comment]
I recently got a production ready push, does it build now?

**Comment by shelbyKiraM** [comment]
Steam complains it's compiled in 32 bit. Rosetta for M1 Macs should actually let it run if it's compiled for macOS as 64 bit.

**Comment by shelbyKiraM** [comment]
```
UnityException: Tried to build game without specifying build directory!
Build.get_outputDirectory () (at Assets/KoboldKare/Scripts/Build.cs:21)
Build.BuildMac () (at Assets/KoboldKare/Scripts/Build.cs:49)
```

**Comment by naelstrof** [comment]
Okay thank you!


> ```
> UnityException: Tried to build game without specifying build directory!
> Build.get_outputDirectory () (at Assets/KoboldKare/Scripts/Build.cs:21)
> Build.BuildMac () (at Assets/KoboldKare/Scripts/Build.cs:49)
> ```

Don't run the KoboldKare continuous integration builders. Just build the game normally (File->Build Settings->Build).

**Comment by naelstrof** [comment]
Oh shoot, I can see in my logs, even though my CI says everything worked successfully-- my logs report an error

```
Building Builds/KoboldKare.app/Contents/PlugIns/audioplugin_phonon.bundle/Contents/_CodeSignature/CodeResources failed with output:
Failed because this command failed to write the following output files:
Builds/KoboldKare.app/Contents/PlugIns/audioplugin_phonon.bundle/Contents/_CodeSignature/CodeResources
```

I'm looking into it!

**Comment by naelstrof** [comment]
Fixed that and failed again at these errors:
```
Building Builds/KoboldKare.app/Contents/Frameworks/libmonobdwgc-2.0.dylib failed with output:
The properties of source file /home/jenkins/Unity/Hub/Editor/2021.3.6f1/Editor/Data/PlaybackEngines/MacStandaloneSupport/Variations/macos_x64ARM64_player_nondevelopment_mono/UnityPlayer.app/Contents/Frameworks/libmonobdwgc-2.0.dylib could not be retrieved: No such file or directory
Building Builds/KoboldKare.app/Contents/Frameworks/libMonoPosixHelper.dylib failed with output:
The properties of source file /home/jenkins/Unity/Hub/Editor/2021.3.6f1/Editor/Data/PlaybackEngines/MacStandaloneSupport/Variations/macos_x64ARM64_player_nondevelopment_mono/UnityPlayer.app/Contents/Frameworks/libMonoPosixHelper.dylib could not be retrieved: No such file or directory
Building Builds/KoboldKare.app/Contents/Resources/unity default resources failed with output:
The properties of source file /home/jenkins/Unity/Hub/Editor/2021.3.6f1/Editor/Data/PlaybackEngines/MacStandaloneSupport/Variations/macos_x64ARM64_player_nondevelopment_mono/UnityPlayer.app/Contents/Resources/unity default resources could not be retrieved: No such file or directory
```

And found the following thread, bug report, and solution here: https://forum.unity.com/threads/linux-command-line-build-of-macos-has-wrong-mono-path.1200499/

I'm kind of amazed that we'd suffer from a case-sensitivity issue. Seems like something that would immediately be caught by any kind of unit test. I'm guessing all their unit tests are running on Windows lol.

Still on it.

**Comment by naelstrof** [comment]
```
##### Failed because this command failed to write the following output files:
Builds/KoboldKare.app/Contents/_CodeSignature/CodeResources
##### Output
System.AggregateException: One or more errors occurred. (Could not find executable at '/home/jenkins/buildAgentFull/work/58b52621821d7add/Builds/KoboldKare.app/Contents/PlugIns/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon' inside a bundle.)
```
Back to ghost phonon plugins. Working on figuring out where it's finding phonon in the project, as it's been totally removed. Guessing I just need to delete the Library folder.

**Comment by naelstrof** [comment]
Got it!!
```
*** Tundra build success (5.12 seconds), 254 items updated, 370 evaluated
```

**Comment by naelstrof** [comment]
Okay, try out the newest Steam build. Hopefully that works for you!

**Comment by naelstrof** [comment]
I received confirmation from another M1 Mac user that the game does indeed work. Let me know if you have any other issues!

**Comment by shelbyKiraM** [comment]
Can confirm AAAAA so happy now, thanks @naelstrof!!
