### ISSUE TITLE
Game stuck on loading screen on macOS

### ISSUE THREAD

**Issue by korochun** [naelstrof/KoboldKare#79]
Built the latest version for macOS, tried on both Intel and Apple Silicon macs. The build goes fine and the main menu works, but after pressing play it goes into the loading screen, seemingly forever. Changing the options doesn't help. Haven't tried on other OSes.

**Comment by naelstrof** [comment]
Yeah sorry, this was because I accidentally dereferenced MainMap in the build settings.
