### ISSUE TITLE
Grab/hold button

### ISSUE THREAD

**Issue by moresmallerbear** [naelstrof/KoboldKare#8]
I know inventory is a dead end, but may I suggest:

Clicking the mouse picks up items without having to hold on to the button, left clicking just continues to pick up other items. Right click sets down, maybe use a modifier like control or shift to throw items as the right click button does now.

or,

Keep the current system, and maybe toggle the above grab system with caps lock or another modifier.

**Comment by naelstrof** [comment]
The pickup and grab system definitely needs revisioning, I think you're right that there should be a method for picking up items without holding keys down, that'd be a good quality of life improvement.
