### ISSUE TITLE
Can't play saved Multiplayer game

### ISSUE THREAD

**Issue by MindlessBabbler** [naelstrof/KoboldKare#84]
Whenever my friend does a multiplayer game she cannot load the save game the next time we try to play a session.

1. Goes to multiplayer and creates a new private game.
2. Loads in alone and tries to load the save from the previous multiplayer game.
3. Gets "Fail to Load Save"
![image1](https://user-images.githubusercontent.com/42722288/209801407-d4a43872-e166-4006-b4b1-0f437ba9129c.png)
![image](https://user-images.githubusercontent.com/42722288/209801411-5f556432-ab63-4d9e-bb9e-9ab174767d4c.png)

**Comment by naelstrof** [comment]
Which version of KoboldKare is this? The update a few hours ago might've already fixed this issue.
(Specifically patch f5e45a8a181d63af5ff59362d3a09db8c0f24aa8)

**Comment by naelstrof** [comment]
While there might be other save bugs, I did fix a number of these issues. Closing. Make a new issue if the issue persists.
