### ISSUE TITLE
Buggy Door in shop

### ISSUE THREAD

**Issue by Godeken** [naelstrof/KoboldKare#85]
You can now walk through this door? not sure if its a bug or intentional...
![image](https://user-images.githubusercontent.com/121225143/210026140-bfb09c54-f594-4fc1-8a4a-aa8d7c35cb79.png)

**Comment by naelstrof** [comment]
It was intentional, might need a "secret found" SFX or meaningful thing back there. Or maybe I should just make the door have collision again haha.

**Comment by Godeken** [comment]
Reward the player... A special type of clothing? :P

**Comment by Godeken** [comment]
Door is blocked again like it should be.
