### ISSUE TITLE
Two Star Quests and purchasables

### ISSUE THREAD

**Issue by Godeken** [naelstrof/KoboldKare#86]
When you purchase the grinder, you go to star level 2- but you cannot buy anything at this level on this wall? Bug or maybe the requirement is not the same as the visual on the wall:
![image](https://user-images.githubusercontent.com/121225143/210026234-46f4050e-2d29-4bd7-86c3-68817ff95f1b.png)

**Comment by Godeken** [comment]
Suggestion: set this higher to like 4... reason being, after you get the grinder, you dont want them to just spam buy everything else. You want them to still go grind fruit and lay two eggs... after the cave mission, then it should be ok to get these because thats when you learn to mix fluids...

**Comment by naelstrof** [comment]
Buying the grinder brings you to star level 3. Not replicable.
