### ISSUE TITLE
Stuck on Main Menu

### ISSUE THREAD

**Issue by Godeken** [naelstrof/KoboldKare#88]
Not sure why I keep finding weird bugs like this... went to save to end my session tonight (its 4AM here), but couldnt get back to the game... like my "focus" was still on the game, but the camera was not going back to the Kobold/Player... i will try recreate and save a recording if i can. This is the second time its happened to me.

**Comment by naelstrof** [comment]
Most of everything involving player spawning, world loading, and map selection has changed dramatically since this issue was created. While I don't know if it's fixed, I also can't confirm its existence. Closing.
