### ISSUE TITLE
Garden

### ISSUE THREAD

**Issue by Arbinator** [naelstrof/KoboldKare#9]
Some kind of garden upgrade where you can grow whatever fruits you want. Small enough so that optimally you would be growing one kind of fruit rather than all of them. Could remove some of the tedium of running out into the woods to grab melons every day once you're far enough to purchase the garden.

**Comment by naelstrof** [comment]
I do want adventuring to be a core aspect of the game, but right now there's not much to adventure, and you're right there should be some quality of life upgrades. I'm definitely planning on an upgrade to the farm to allow for growing fruits.
