### ISSUE TITLE
Piled fruit is saved without rotations.

### ISSUE THREAD

**Issue by naelstrof** [naelstrof/KoboldKare#94]
Causes them to explode on load.

![image](https://user-images.githubusercontent.com/1131571/210131442-7e74164a-4f13-4218-ac5c-0cdd816f7338.png)

![image](https://user-images.githubusercontent.com/1131571/210131445-d7cbf62d-c44a-4587-904c-9d87dab4890d.png)

**Comment by Godeken** [comment]
Could it not also be due to the way the system loads - Creates objects first and then moves them to position? That movement could also create the explosion

Idea: disable Ragdoll and JigglePhysics during loading (make a "Loading" state) and after load, re-enable it all?
