### ISSUE TITLE
Issue with purchases at 6Star... you can still buy more but theres nothing to buy

### ISSUE THREAD

**Issue by Godeken** [naelstrof/KoboldKare#96]
![image](https://user-images.githubusercontent.com/121225143/210134165-55e96727-ace0-4996-be73-f10f8d315c06.png)
I can still buy more even though theres nothing to buy... not sure if its an official bug as i used "skip".

**Comment by naelstrof** [comment]
Couldn't replicate in the current version. Must've been fixed at some point.
